### ISSUE TITLE
RBS support progress tracking

### ISSUE THREAD

**Issue by AaronC81** [AaronC81/parlour#95]
#94 adds the basics of RBS support to Parlour, but there are still other things that should be supported or added for the best experience. This issue is designed to track them. Please feel free to give any of them a shot and open a PR :smile: 

------

Initial batch of things to add:
- [X] f6a9f60 Add RBS interfaces
- [X] 20df869 Fix comments (Sord doesn't generate them properly)
- [X] c168735 Add `.parlour` options for specifying output format(s)
- [X] 90f42e2 Decouple `Types::Proc` from `RbiGenerator::Parameter`
- [X] 43f1bef Add method overload tests
- [X] 5a46a7e Add `Conversion::Converter` tests
- [X] 0879867 Add support for type aliases 
- [X] 18b0754 Make output RBS files match requested formatting
- [X] 3601b7c Add `generalize_from_rbi!` support for more Sorbet types
- [X] 3b04979 Handle type generalisation warnings in a better way than `puts`
- [X] 3b04979 Make user aware of `Conversion::Converter` warnings
- [X] d0d6959 (This was an internal bug, not incorrect ordering) ~Handle parameters in the wrong order (i.e. optional before positional) more elegantly (encountered running Sord on Bundler)~
- [X] Update README (4a791e4) and other docs
- [X] b913f82 bf4e129 Add one-way conversion of RBI structs/enums to RBS

(Released as 5.0.0.beta.1)

------

New things, after trying to integrate 5.0.0.beta.1 into Sord:
- [x] `Types::Self`
- [x] Syntax-agnostic "describe" for `Types`, with output like `Array<Nilable<Union<String, Integer>>>` (for better `SORD_ERROR_` constant names)
- [x] Better `eql?`/`hash` behaviour for `Types`

(Released as 5.0.0.beta.2)

------

In future, I'll look into adding type parsing/loading/conflict resolution for RBS.

**Comment by AaronC81** [comment]
Preliminary RBS support has now been merged!
